### ISSUE TITLE
Список ошибок Unknown MDO при анализе выгрузки УХ

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/mdclasses#81]
```
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 529b6fd5-53c3-4df8-9f1e-430095302b15
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 17032fc0-a87f-46d0-a3c5-36c816e59e9b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 8cd136bf-99b4-4b79-84b3-ef42516d839f
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 6a1acbcb-6332-491a-8581-cd61a4b5afed
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO cbcf641e-8155-46e6-8867-3d09bfbf29ae
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO f85b5533-4e10-4eac-8a7c-d1f5f74f9fce
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0ee06662-6b22-4d58-a1a8-0b9e22eb120e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 8c40576b-eebb-4d20-bdcd-935d060105c7
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 2e7eef07-e8e9-4769-94fc-da7ee6315080
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO dc5367ce-822f-4ad2-b6bf-51a1a72ab6e6
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO bc65cc19-d50d-4d39-916a-96beadd83b83
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0ec38892-ed90-437c-b5f1-ffc8f5d6a32e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 54c91572-2089-43e2-bb64-1148f9dca369
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c158e966-d2df-47e6-bc26-c62cdfb43dc0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 17d1aed1-e112-40d9-80b8-544fb115a018
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 9e3d65d6-82e6-4ba1-b7dd-7dbe763a716e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO d8430c84-9dae-41cb-a876-53480851e3b1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 188ac962-62d7-4b60-bd80-a3e7a8629a58
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO fc8d031c-e110-410f-a795-dc03891ef67b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 60aaa289-1f07-438c-8f10-81058ac671c3
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 4f6cebed-72e9-4253-93f6-2b9013fcbef2
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0b05e754-f64b-4976-b0f1-12c84b509997
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e9d9b9f6-1beb-4143-8dc1-746ce5bf6d50
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO b282b49a-cb71-41df-93ec-737a91ea7ae3
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO b01ae079-0d91-4775-a666-cc8e3e00f7e6
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO dc3b5269-4c12-44fe-9f75-bdf35568e30c
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 496e7ed0-dff4-4cda-b2da-6b4b51037126
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0748dc95-2c57-4ce7-bf79-df79b6f098bb
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 49bbd223-82b7-4085-ac6f-66b8c86d821e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO b9426802-932d-436b-b891-9266ea24bbc1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 05072a66-7a8f-4aee-802d-9d5057f98dcc
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e71fd5cf-7fb9-4676-a2f6-8b86a5c6ca82
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e77ed360-6476-4054-b987-3f095f195763
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e594ee18-b30a-4a5a-948e-0e4a40933101
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 773f9eb2-2c23-491a-b074-4f78dfa2363c
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 75f37e1b-e758-4ad2-bb0a-a459a84369e3
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 69863e71-7e7b-48d8-bebc-7dda330e997d
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 418deaa0-683e-4862-9348-c0086ba6909f
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e39f4954-10f7-457b-ab0b-a565d9d28236
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 9378a2bb-f32b-410e-afdf-c8b908ce97d9
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 5fd1ce0f-84fc-41b7-bcb4-1b476590ee6e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 00c96b03-ac85-48af-80b1-9f42fcbbb9c7
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 9b29d798-967e-4c3f-8cf3-22359db141c0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO f17ef62d-2a16-4d1d-a2e4-ee636c51f624
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c5a60b5b-3f51-48ce-84fb-02f2d7df8020
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a752fba8-5084-4fa2-9d0b-7074a42b1312
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 68f6d1b2-9c08-4b37-ba23-1e15539a9c35
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO cb6df70e-c7cd-4343-bfa9-5bdb907b4580
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO Subsystem.СтандартныеПодсистемы.Subsystem.КалендарныеГрафики
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO Subsystem.СтандартныеПодсистемы.Subsystem.ЗапретРедактированияРеквизитовОбъектов
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e79ebe5b-d81d-4735-87bf-ec891ccff186
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 23d4aa7d-8a2c-4e18-9d5d-43a155de9bf0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 9fc7e672-6c80-418a-a973-937a4a172a2b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO ffd8f84f-e7b4-44fd-ad44-980fa0090af4
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 74e1bfac-18ea-48c2-b7e9-fd374a90a35d
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO Subsystem.СтандартныеПодсистемы.Subsystem.КонтактнаяИнформация
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 29c37223-de1c-49fb-8488-77e44dd79edd
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e3476d0e-0ab4-4734-9261-04aef6281086
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0b8c7a82-9865-4c5e-9bf1-ba6a7ef3a5d1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO d509d058-f519-43a3-ba8b-1ef48fa18140
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 2643dff7-1c84-4a6b-b8be-f15a4161ba4b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c4f5229a-b702-428a-83b3-482168afd03e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 07ca00fe-0f77-4d83-9424-9d61f5392e50
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO af099033-64ca-4549-adfa-f8de495a4063
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO b7009ca4-3c35-4ac2-89dc-38953ef8afd8
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 91cadbe5-a2aa-435b-acf0-00d5d656fe23
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0b05e754-f64b-4976-b0f1-12c84b509997
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e9d9b9f6-1beb-4143-8dc1-746ce5bf6d50
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a4f9038b-96de-4ae0-b19b-64bc6bf90f72
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 98de855b-83bc-499d-bd7f-a51bce433f42
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO d76e6957-ba5a-41dc-adc6-0c21b0960662
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e5d02ba2-3bb3-45bb-b9b1-c350aa0f1cc1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 632e1e96-e911-4430-a104-798431b721c0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0f184dcf-16bd-4ab9-9ef0-34fdb997ff91
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 5ffff00f-ef0d-4ff9-8a6b-565787e31d8a
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 8800a98d-eb56-48b4-8b21-85cf0e2d9b59
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a8e8aea7-9fa4-4b75-bda3-57cc7a2ef2e7
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO bf62c112-92eb-401d-a2ea-b504921736af
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a7bacace-f735-4f74-b8a9-686e1451996b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 76629e70-9ecd-4c94-9acf-aef2af2a2963
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 56f8dd2d-d359-4ff9-a9ba-0cfd2b9015d2
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO bdb2aed0-43db-4d1a-b186-d4dccb29bb5a
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c7074315-ee99-4bb7-be28-34bf3c73ccf3
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 44f9d0e3-d561-41f9-a4ed-ce2c76701a58
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 4e82be02-8c42-4363-a1a3-81128afb7b7f
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 198fc05d-d961-4396-bd20-05229359d973
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 503f49da-2e8b-48c9-86a0-2ccd1cd0ca8a
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 138ad3bc-beaf-4a88-91f3-39fb44a2aad2
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 247922e9-6f2d-4929-90e3-3292fd3d97ae
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 6702a88c-c122-4015-ac33-1bcb5aba3edd
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 75f3866f-e972-482a-95c7-44ca5e291315
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 56a1b62d-6678-4eb7-b0f8-bca2edf8217e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 10b80712-f4b3-4e9d-83e0-ec49cd1bb0e0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 031a96a5-a59f-460f-9b04-bebd86308ea5
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 5adbca86-b909-400c-a5d5-cfddc8c2219c
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 9afa4640-4fe4-49cd-a056-ab24ced0d9c2
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 83713346-d2c2-4835-9b28-7c81e749a432
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO ad04ca74-c0d7-4861-b0d9-09cdcce9a8fc
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO b3249a13-f229-45c5-a0d4-56878e66d45b
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 526ae7c1-28f3-4278-86f4-f912779a22b1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e66f1399-afcf-4c5e-aa51-e6048dcf72eb
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 14e5cc35-cd3f-485d-b7c9-d2b895cb63e9
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 0e5cadc1-4575-42c9-bfcb-a7858b83d841
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a99b75b4-8e49-4e46-8df8-c58c5aa08d77
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO db8c07bb-61d7-4026-a20f-811bed0a743a
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 32d05859-da06-439e-b7ea-bddcd37d25d0
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO aec02467-aaba-4758-b04c-49e03b20e877
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c92eefd6-18b1-4b9a-a9d6-a638077945c5
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO a7af75e2-7b5a-478a-9cea-db53f812db9f
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO e41829f6-e3fe-4a97-aa3c-6e0c841d95fb
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 61fdd8de-2737-4623-a5fc-a2d468f0f268
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 4fe8560a-a7aa-4798-a121-14b5e073d964
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 51b5e282-ba9a-47cf-8baf-5799aa28c8f1
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO caac9c5f-80b3-4351-805c-fba9d7845420
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO fe4bd7d0-0a61-4ca8-9884-130ae2cd72bf
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO 8b9becbb-3554-4662-9984-e94e0c503707
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO ce06bbae-443c-44ea-8e40-6b27e852cb5e
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO c9a0f5c3-3c93-46eb-862c-e3cfee8f840a
[ForkJoinPool.commonPool-worker-27] ERROR com.github._1c_syntax.mdclasses.utils.MDOUtils - Unknown MDO eb120db5-8ed2-45ae-9993-f4cd48e6a99d
```

**Comment by qtLex** [comment]
У меня еще дополняется подобными ошибками
```
09:51:29  ERROR: Unknown MDO 97a34ca4-3f83-4cd5-a5e8-46d05e5fd415
09:51:29  ERROR: Unknown MDO b9d5b42d-94ba-4cb4-8c58-5a46f07c87e1
09:51:29  ERROR: Unknown MDO ffb55e1a-d5a4-4312-9583-58d8a8fe5f22
09:51:29  ERROR: Unknown MDO f8f4a594-8d59-49a2-9772-1a1e19c4f871
09:51:29  ERROR: Unknown MDO 757a6b46-9ad4-4f41-8c53-7f4856376d86
09:51:29  ERROR: Unknown MDO 04877e77-377d-4c35-835b-2753211adb3d
09:51:29  ERROR: N/A
09:51:29   at [Source: (File); line: 57, column: 16] (through reference chain: com.github._1c_syntax.mdclasses.mdo.MetaDataObject["Subsystem"]->com.github._1c_syntax.mdclasses.mdo.Subsystem$SubsystemBuilderImpl["Properties"])
09:51:29  com.fasterxml.jackson.databind.JsonMappingException: N/A
09:51:29   at [Source: (File); line: 57, column: 16] (through reference chain: com.github._1c_syntax.mdclasses.mdo.MetaDataObject["Subsystem"]->com.github._1c_syntax.mdclasses.mdo.Subsystem$SubsystemBuilderImpl["Properties"])
09:51:29  	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:281)
09:51:29  	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:611)
09:51:29  	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:599)
09:51:29  	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:173)
09:51:29  	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269)
09:51:29  	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
09:51:29  	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
09:51:29  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
09:51:29  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
09:51:29  	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
09:51:29  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
09:51:29  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
09:51:29  	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
09:51:29  	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)
09:51:29  	at com.github._1c_syntax.mdclasses.utils.MDOUtils.getMDObject(MDOUtils.java:122)
09:51:29  	at com.github._1c_syntax.mdclasses.utils.MDOUtils.lambda$computeChildren$6(MDOUtils.java:332)
09:51:29  	at java.base/java.lang.Iterable.forEach(Unknown Source)
09:51:29  	at com.github._1c_syntax.mdclasses.utils.MDOUtils.computeChildren(MDOUtils.java:327)
09:51:29  	at com.github._1c_syntax.mdclasses.utils.MDOUtils.lambda$getAllChildren$5(MDOUtils.java:307)
09:51:29  	at java.base/java.lang.Iterable.forEach(Unknown Source)
09:51:29  	at com.github._1c_syntax.mdclasses.utils.MDOUtils.getAllChildren(MDOUtils.java:307)
09:51:29  	at com.github._1c_syntax.mdclasses.metadata.Configuration.<init>(Configuration.java:104)
09:51:29  	at com.github._1c_syntax.mdclasses.metadata.Configuration.create(Configuration.java:142)
09:51:29  	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.computeConfigurationMetadata(ServerContext.java:104)
09:51:29  	at com.github._1c_syntax.utils.Lazy.maybeCompute(Lazy.java:72)
09:51:29  	at com.github._1c_syntax.utils.Lazy.getOrCompute(Lazy.java:49)
09:51:29  	at com.github._1c_syntax.utils.Lazy.getOrCompute(Lazy.java:57)
09:51:29  	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getConfiguration(ServerContext.java:96)
09:51:29  	at com.github._1c_syntax.bsl.languageserver.diagnostics.DiagnosticSupplier.getDiagnosticInstances(DiagnosticSupplier.java:79)
09:51:29  	at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.computeDiagnostics(DiagnosticProvider.java:74)
09:51:29  	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:194)
09:51:29  	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:171)
09:51:29  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
09:51:29  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
09:51:29  	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
09:51:29  	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
09:51:29  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
09:51:29  Caused by: java.lang.NullPointerException: null
09:51:29  	at com.github._1c_syntax.mdclasses.mdo.Subsystem$SubsystemBuilderImpl.lambda$childrenAdd$0(Subsystem.java:131)
09:51:29  	at java.base/java.util.ArrayList.forEach(Unknown Source)
09:51:29  	at com.github._1c_syntax.mdclasses.mdo.Subsystem$SubsystemBuilderImpl.childrenAdd(Subsystem.java:131)
09:51:29  	at com.github._1c_syntax.mdclasses.mdo.Subsystem$SubsystemBuilderImpl.properties(Subsystem.java:118)
09:51:29  	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
09:51:29  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
09:51:29  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
09:51:29  	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:170)
09:51:29  	... 38 common frames omitted
09:51:29  
```

**Comment by artbear** [comment]
при анализе одних и тех же исходников получаю странное - в основном ошибки повторяются, но иногда появляются новые ошибки (

![image](https://user-images.githubusercontent.com/2920817/82122227-eae73480-979a-11ea-8d09-3b124dd1c1bd.png)
